export FUEL_DATA_PATH=$PWD
for TRAIN_SIZE in {100000..700000..100000}
do
  for VOCAB_SIZE in {1000..9000..1000}
  do
    TRAIN_SIZE=$TRAIN_SIZE VOCAB_SIZE=$VOCAB_SIZE msub -v TRAIN_SIZE,VOCAB_SIZE,FUEL_DATA_PATH -e ${TRAIN_SIZE}_${VOCAB_SIZE}.err -o ${TRAIN_SIZE}_${VOCAB_SIZE}.out feedforward.pbs
  done
done
